<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.cloudpivot.starter</groupId>
        <artifactId>cloudpivot-starter</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>cloudpivot-starter-license</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>CloudPivot Starter License模块</description>

    <modules>
        <module>cloudpivot-starter-license-core</module>
        <module>cloudpivot-starter-license-generator</module>
        <module>cloudpivot-starter-license-verifier</module>
    </modules>
</project>