<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.cloudpivot.starter</groupId>
        <artifactId>cloudpivot-starter-data</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>cloudpivot-starter-data-mp</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>CloudPivot Starter ?????? - MyBatis Plus</description>

    <dependencies>
        <!-- ?????? - ???? -->
        <dependency>
            <groupId>com.cloudpivot.starter</groupId>
            <artifactId>cloudpivot-starter-data-core</artifactId>
        </dependency>

        <!-- MyBatis Plus?MyBatis ??????? MyBatis ?????????????????????? -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
        </dependency>
        <!-- MyBatis Plus jsqlparser ????????????? -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-jsqlparser</artifactId>
        </dependency>

        <!-- P6Spy?SQL ??????? -->
        <dependency>
            <groupId>p6spy</groupId>
            <artifactId>p6spy</artifactId>
        </dependency>

        <!-- CosId?????????????? ID ???? -->
        <dependency>
            <groupId>me.ahoo.cosid</groupId>
            <artifactId>cosid-spring-boot-starter</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>
