<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.cloudpivot.starter</groupId>
        <artifactId>cloudpivot-starter</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>cloudpivot-starter-ratelimiter</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>CloudPivot Starter 限流模块</description>

    <dependencies>
        <!-- 核心模块 -->
        <dependency>
            <groupId>com.cloudpivot.starter</groupId>
            <artifactId>cloudpivot-starter-core</artifactId>
        </dependency>

        <!-- 缓存模块 - Redisson -->
        <dependency>
            <groupId>com.cloudpivot.starter</groupId>
            <artifactId>cloudpivot-starter-cache-redisson</artifactId>
        </dependency>
    </dependencies>
</project>
