<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cc.cloudpivot.starter</groupId>
        <artifactId>cloudpivot-starter-auth</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>cloudpivot-starter-auth-justauth</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>CloudPivot Starter 认证模块 - JustAuth</description>

    <dependencies>
        <dependency>
            <groupId>cc.cloudpivot.starter</groupId>
            <artifactId>cloudpivot-starter-cache-redisson</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>me.zhyd.oauth</groupId>
            <artifactId>JustAuth</artifactId>
        </dependency>
    </dependencies>
</project>
